name: CI/CD ${{ github.ref == 'refs/heads/master' && 'production' || 'homolog' }}

on:
  push:
    branches: [ master, homolog ]
  workflow_dispatch:
jobs:
  deploy:
    environment:
      name: ${{ github.ref == 'refs/heads/master' && 'production' || 'homolog' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Run a generic echo
        run: echo Hello, world!

      - name: Run a dynamic echo
        run: |
          echo ${{ secrets.message }}
